
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module DE10_LITE_PARCIAL_2(

	//////////// CLOCK //////////
	input 		          		ADC_CLK_10,
	input 		          		MAX10_CLK1_50,
	input 		          		MAX10_CLK2_50,

	//////////// SEG7 //////////
	output		     [7:0]		HEX0,
	output		     [7:0]		HEX1,
	output		     [7:0]		HEX2,
	output		     [7:0]		HEX3,
	output		     [7:0]		HEX4,
	output		     [7:0]		HEX5,

	//////////// KEY //////////
	input 		     [1:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// GPIO, GPIO connect to GPIO Default //////////
	inout 		    [35:0]		GPIO
);



//=======================================================
//  REG/WIRE declarations
//=======================================================




//=======================================================
//  Structural coding
//=======================================================

parcial2 parcial2_inst
(
	.clk(MAX10_CLK1_50) ,	// input  clk_sig
	.entrada(GPIO[0]) ,	// input  entrada_sig
	.entrada_sal(GPIO[3]) ,	// input  entrada_sig
	.motor(GPIO[2]) ,	// output  motor_sig
	.salida(GPIO[1]) ,	// input  salida_sig
	.salida_sal(GPIO[4]), 	// input  salida_sig
	.reset(KEY[0]) ,	// input  reset_sig
	.LEDS(HEX0[7:0]) ,	// output [7:0] LEDS_sig
	.LEDS_DEC(HEX1[7:0]) 	// output [7:0] LEDS_DEC_sig
);

endmodule
