// Copyright (C) 2022  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 21.1 (Build Build 850 06/23/2022)
// Created on Thu Oct 27 10:25:53 2022

DE10_LITE_PARCIAL_2 DE10_LITE_PARCIAL_2_inst
(
	.ADC_CLK_10(ADC_CLK_10_sig) ,	// input  ADC_CLK_10_sig
	.MAX10_CLK1_50(MAX10_CLK1_50_sig) ,	// input  MAX10_CLK1_50_sig
	.MAX10_CLK2_50(MAX10_CLK2_50_sig) ,	// input  MAX10_CLK2_50_sig
	.HEX0(HEX0_sig) ,	// output [7:0] HEX0_sig
	.HEX1(HEX1_sig) ,	// output [7:0] HEX1_sig
	.HEX2(HEX2_sig) ,	// output [7:0] HEX2_sig
	.HEX3(HEX3_sig) ,	// output [7:0] HEX3_sig
	.HEX4(HEX4_sig) ,	// output [7:0] HEX4_sig
	.HEX5(HEX5_sig) ,	// output [7:0] HEX5_sig
	.KEY(KEY_sig) ,	// input [1:0] KEY_sig
	.LEDR(LEDR_sig) ,	// output [9:0] LEDR_sig
	.SW(SW_sig) ,	// input [9:0] SW_sig
	.GPIO(GPIO_sig) 	// inout [35:0] GPIO_sig
);

