// Copyright (C) 2022  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 21.1 (Build Build 850 06/23/2022)
// Created on Thu Oct 27 11:15:53 2022

parcial2 parcial2_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.entrada(entrada_sig) ,	// input  entrada_sig
	.entrada_sal(entrada_sal_sig) ,	// input  entrada_sal_sig
	.motor(motor_sig) ,	// output  motor_sig
	.salida(salida_sig) ,	// input  salida_sig
	.salida_sal(salida_sal_sig) ,	// input  salida_sal_sig
	.reset(reset_sig) ,	// input  reset_sig
	.LEDS(LEDS_sig) ,	// output [7:0] LEDS_sig
	.LEDS_DEC(LEDS_DEC_sig) 	// output [7:0] LEDS_DEC_sig
);

